<a href="https://colab.research.google.com/github/abulhassanraza/deep_learning_assignments/blob/main/Ionosphere_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
import numpy as np
import pandas as pd
from keras.layers import Dense

In [37]:
data = pd.read_csv('ionosphere_data.csv')

In [38]:
data.head()

   feature1  feature2  feature3  ...  feature33  feature34  label
0         1         0   0.99539  ...    0.18641   -0.45300      g
1         1         0   1.00000  ...   -0.13738   -0.02447      b
2         1         0   1.00000  ...    0.56045   -0.38238      g
3         1         0   1.00000  ...   -0.32382    1.00000      b
4         1         0   1.00000  ...   -0.04608   -0.65697      g

[5 rows x 35 columns]

In [39]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 351 entries, 0 to 350
Data columns (total 35 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   feature1   351 non-null    int64
 1   feature2   351 non-null    int64
 2   feature3   351 non-null    float64
 3   feature4   351 non-null    float64
 4   feature5   351 non-null    float64
 5   feature6   351 non-null    float64
 6   feature7   351 non-null    float64
 7   feature8   351 non-null    float64
 8   feature9   351 non-null    float64
 9   feature10  351 non-null    float64
 10  feature11  351 non-null    float64
 11  feature12  351 non-null    float64
 12  feature13  351 non-null    float64
 13  feature14  351 non-null    float64
 14  feature15  351 non-null    float64
 15  feature16  351 non-null    float64
 16  feature17  351 non-null    float64
 17  feature18  351 non-null    float64
 18  feature19  351 non-null    float64
 19  feature20  351 non-null    float64
 20  feature21  351 non-null    float64
 21  feature22  351 non-null    float64
 22  feature23  351 non-null    float64
 23  feature24  351 non-null    float64
 24  feature25  351 non-null    float64
 25  feature26  351 non-null    float64
 26  feature27  351 non-null    float64
 27  feature28  351 non-null    float64
 28  feature29  351 non-null    float64
 29  feature30  351 non-null    float64
 30  feature31  351 non-null    float64
 31  feature32  351 non-null    float64
 32  feature33  351 non-null    float64
 33  feature34  351 non-null    float64
 34  label      351 non-null    object
dtypes: float64(32), int64(2), object(1)
memory usage: 96.1+ KB

In [40]:
data.isnull().sum()

feature1     0
feature2     0
feature3     0
feature4     0
feature5     0
feature6     0
feature7     0
feature8     0
feature9     0
feature10    0
feature11    0
feature12    0
feature13    0
feature14    0
feature15    0
feature16    0
feature17    0
feature18    0
feature19    0
feature20    0
feature21    0
feature22    0
feature23    0
feature24    0
feature25    0
feature26    0
feature27    0
feature28    0
feature29    0
feature30    0
feature31    0
feature32    0
feature33    0
feature34    0
label        0
dtype: int64

In [41]:
data.isna().sum()

feature1     0
feature2     0
feature3     0
feature4     0
feature5     0
feature6     0
feature7     0
feature8     0
feature9     0
feature10    0
feature11    0
feature12    0
feature13    0
feature14    0
feature15    0
feature16    0
feature17    0
feature18    0
feature19    0
feature20    0
feature21    0
feature22    0
feature23    0
feature24    0
feature25    0
feature26    0
feature27    0
feature28    0
feature29    0
feature30    0
feature31    0
feature32    0
feature33    0
feature34    0
label        0
dtype: int64

In [42]:
data.describe()

         feature1  feature2    feature3  ...   feature32   feature33   feature34
count  351.000000     351.0  351.000000  ...  351.000000  351.000000  351.000000
mean     0.891738       0.0    0.641342  ...   -0.003794    0.349364    0.014480
std      0.311155       0.0    0.497708  ...    0.513574    0.522663    0.468337
min      0.000000       0.0   -1.000000  ...   -1.000000   -1.000000   -1.000000
25%      1.000000       0.0    0.472135  ...   -0.242595    0.000000   -0.165350
50%      1.000000       0.0    0.871110  ...    0.000000    0.409560    0.000000
75%      1.000000       0.0    1.000000  ...    0.200120    0.813765    0.171660
max      1.000000       0.0    1.000000  ...    1.000000    1.000000    1.000000

[8 rows x 34 columns]

In [43]:
data.drop(columns='feature2', inplace=True)

In [44]:
data.label.value_counts

<bound method IndexOpsMixin.value_counts of 0      g
1      b
2      g
3      b
4      g
      ..
346    g
347    g
348    g
349    g
350    g
Name: label, Length: 351, dtype: object>

In [45]:
encoded_values = {'label': {'g':0, 'b':1}}

In [46]:
df = data.replace(encoded_values)

In [47]:
y = df.label
x = df.drop(columns='label')

In [48]:
df.head()

   feature1  feature3  feature4  ...  feature33  feature34  label
0         1   0.99539  -0.05889  ...    0.18641   -0.45300      0
1         1   1.00000  -0.18829  ...   -0.13738   -0.02447      1
2         1   1.00000  -0.03365  ...    0.56045   -0.38238      0
3         1   1.00000  -0.45161  ...   -0.32382    1.00000      1
4         1   1.00000  -0.02401  ...   -0.04608   -0.65697      0

[5 rows x 34 columns]

In [49]:
y

0      0
1      1
2      0
3      1
4      0
      ..
346    0
347    0
348    0
349    0
350    0
Name: label, Length: 351, dtype: int64

In [50]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size= 0.40)

In [51]:
x_train

     feature1  feature3  feature4  ...  feature32  feature33  feature34
89          1   0.41932   0.12482  ...   -0.07464   -0.00526   -0.06314
180         1   1.00000   1.00000  ...    0.20175    0.82895    0.07895
35          1   0.66161  -1.00000  ...    0.65268    1.00000    0.34732
96          1   0.90116   0.16607  ...   -0.05525   -0.67699   -0.19904
213         1   1.00000   0.14286  ...    0.57143    1.00000    0.00000
..        ...       ...       ...  ...        ...        ...        ...
142         1   1.00000  -0.05529  ...   -0.63156    1.00000   -0.65935
118         1   0.39286   0.52381  ...   -0.29915    0.25441   -0.55837
7           0   0.00000   0.00000  ...    1.00000    0.00000    0.00000
266         1   0.76627   0.21106  ...   -0.24648   -0.11894   -0.27218
263         1   0.89410   0.13425  ...    0.19172   -0.48808    0.05972

[210 rows x 33 columns]

In [52]:
y_train

89     1
180    1
35     1
96     0
213    0
      ..
142    1
118    1
7      1
266    0
263    0
Name: label, Length: 210, dtype: int64

In [53]:
from keras.models import Sequential
from keras import regularizers

In [56]:
model = Sequential()
model.add(Dense(14, activation= 'sigmoid',input_shape= (33,)))
model.add(Dense(1, activation='sigmoid'))

In [57]:
model.compile(optimizer='Adam', loss= 'binary_crossentropy', metrics= 'accuracy')

In [59]:
model.fit(x_train, y_train, epochs= 100, batch_size= 8)

Epoch 1/100
27/27 [==============================] - 1s 1ms/step - loss: 0.6839 - accuracy: 0.5339
Epoch 2/100
27/27 [==============================] - 0s 1ms/step - loss: 0.6114 - accuracy: 0.6547
Epoch 3/100
27/27 [==============================] - 0s 2ms/step - loss: 0.5927 - accuracy: 0.7035
Epoch 4/100
27/27 [==============================] - 0s 1ms/step - loss: 0.5990 - accuracy: 0.6821
Epoch 5/100
27/27 [==============================] - 0s 1ms/step - loss: 0.6020 - accuracy: 0.6650
Epoch 6/100
27/27 [==============================] - 0s 2ms/step - loss: 0.5876 - accuracy: 0.6861
Epoch 7/100
27/27 [==============================] - 0s 1ms/step - loss: 0.5536 - accuracy: 0.7050
Epoch 8/100
27/27 [==============================] - 0s 1ms/step - loss: 0.5300 - accuracy: 0.7511
Epoch 9/100
27/27 [==============================] - 0s 2ms/step - loss: 0.5361 - accuracy: 0.7273
Epoch 10/100
27/27 [==============================] - 0s 1ms/step - loss: 0.5285 - accuracy: 0.7090
Epoch 11/100
27/27 [==============================] - 0s 1ms/step - loss: 0.5329 - accuracy: 0.6955
Epoch 12/100
27/27 [==============================] - 0s 2ms/step - loss: 0.5153 - accuracy: 0.7222
Epoch 13/100
27/27 [==============================] - 0s 2ms/step - loss: 0.5371 - accuracy: 0.7153
Epoch 14/100
27/27 [==============================] - 0s 1ms/step - loss: 0.5458 - accuracy: 0.6858
Epoch 15/100
27/27 [==============================] - 0s 1ms/step - loss: 0.4530 - accuracy: 0.8005
Epoch 16/100
27/27 [==============================] - 0s 1ms/step - loss: 0.4650 - accuracy: 0.7938
Epoch 17/100
27/27 [==============================] - 0s 1ms/step - loss: 0.4844 - accuracy: 0.7791
Epoch 18/100
27/27 [==============================] - 0s 1ms/step - loss: 0.4600 - accuracy: 0.7868
Epoch 19/100
27/27 [==============================] - 0s 1ms/step - loss: 0.4407 - accuracy: 0.8343
Epoch 20/100
27/27 [==============================] - 0s 1ms/step - loss: 0.4596 - accuracy: 0.8018
Epoch 21/100
27/27 [==============================] - 0s 1ms/step - loss: 0.4191 - accuracy: 0.8766
Epoch 22/100
27/27 [==============================] - 0s 2ms/step - loss: 0.4704 - accuracy: 0.8140
Epoch 23/100
27/27 [==============================] - 0s 2ms/step - loss: 0.4206 - accuracy: 0.8402
Epoch 24/100
27/27 [==============================] - 0s 2ms/step - loss: 0.4189 - accuracy: 0.8577
Epoch 25/100
27/27 [==============================] - 0s 1ms/step - loss: 0.4162 - accuracy: 0.8933
Epoch 26/100
27/27 [==============================] - 0s 1ms/step - loss: 0.4198 - accuracy: 0.8499
Epoch 27/100
27/27 [==============================] - 0s 1ms/step - loss: 0.4127 - accuracy: 0.8594
Epoch 28/100
27/27 [==============================] - 0s 1ms/step - loss: 0.4209 - accuracy: 0.8478
Epoch 29/100
27/27 [==============================] - 0s 1ms/step - loss: 0.3751 - accuracy: 0.8843
Epoch 30/100
27/27 [==============================] - 0s 2ms/step - loss: 0.3928 - accuracy: 0.8540
Epoch 31/100
27/27 [==============================] - 0s 1ms/step - loss: 0.3930 - accuracy: 0.8829
Epoch 32/100
27/27 [==============================] - 0s 1ms/step - loss: 0.3826 - accuracy: 0.8623
Epoch 33/100
27/27 [==============================] - 0s 2ms/step - loss: 0.3527 - accuracy: 0.8844
Epoch 34/100
27/27 [==============================] - 0s 2ms/step - loss: 0.3091 - accuracy: 0.8924
Epoch 35/100
27/27 [==============================] - 0s 2ms/step - loss: 0.3529 - accuracy: 0.8931
Epoch 36/100
27/27 [==============================] - 0s 1ms/step - loss: 0.3436 - accuracy: 0.9135
Epoch 37/100
27/27 [==============================] - 0s 2ms/step - loss: 0.3497 - accuracy: 0.8870
Epoch 38/100
27/27 [==============================] - 0s 1ms/step - loss: 0.3385 - accuracy: 0.9020
Epoch 39/100
27/27 [==============================] - 0s 2ms/step - loss: 0.3126 - accuracy: 0.9298
Epoch 40/100
27/27 [==============================] - 0s 2ms/step - loss: 0.3329 - accuracy: 0.9070
Epoch 41/100
27/27 [==============================] - 0s 1ms/step - loss: 0.3078 - accuracy: 0.9118
Epoch 42/100
27/27 [==============================] - 0s 2ms/step - loss: 0.3059 - accuracy: 0.9112
Epoch 43/100
27/27 [==============================] - 0s 2ms/step - loss: 0.3152 - accuracy: 0.8907
Epoch 44/100
27/27 [==============================] - 0s 1ms/step - loss: 0.3070 - accuracy: 0.9069
Epoch 45/100
27/27 [==============================] - 0s 1ms/step - loss: 0.3353 - accuracy: 0.9109
Epoch 46/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2983 - accuracy: 0.8955
Epoch 47/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2766 - accuracy: 0.9344
Epoch 48/100
27/27 [==============================] - 0s 1ms/step - loss: 0.2720 - accuracy: 0.9272
Epoch 49/100
27/27 [==============================] - 0s 1ms/step - loss: 0.2543 - accuracy: 0.9412
Epoch 50/100
27/27 [==============================] - 0s 1ms/step - loss: 0.2885 - accuracy: 0.9087
Epoch 51/100
27/27 [==============================] - 0s 1ms/step - loss: 0.3138 - accuracy: 0.8801
Epoch 52/100
27/27 [==============================] - 0s 1ms/step - loss: 0.3043 - accuracy: 0.8845
Epoch 53/100
27/27 [==============================] - 0s 1ms/step - loss: 0.2704 - accuracy: 0.9244
Epoch 54/100
27/27 [==============================] - 0s 1ms/step - loss: 0.2656 - accuracy: 0.9065
Epoch 55/100
27/27 [==============================] - 0s 1ms/step - loss: 0.2822 - accuracy: 0.9152
Epoch 56/100
27/27 [==============================] - 0s 1ms/step - loss: 0.3103 - accuracy: 0.8874
Epoch 57/100
27/27 [==============================] - 0s 1ms/step - loss: 0.2540 - accuracy: 0.9212
Epoch 58/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2829 - accuracy: 0.8812
Epoch 59/100
27/27 [==============================] - 0s 1ms/step - loss: 0.3044 - accuracy: 0.9109
Epoch 60/100
27/27 [==============================] - 0s 1ms/step - loss: 0.2574 - accuracy: 0.9054
Epoch 61/100
27/27 [==============================] - 0s 1ms/step - loss: 0.2957 - accuracy: 0.8975
Epoch 62/100
27/27 [==============================] - 0s 1ms/step - loss: 0.2404 - accuracy: 0.9285
Epoch 63/100
27/27 [==============================] - 0s 1ms/step - loss: 0.2644 - accuracy: 0.9115
Epoch 64/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2646 - accuracy: 0.9199
Epoch 65/100
27/27 [==============================] - 0s 1ms/step - loss: 0.2520 - accuracy: 0.9145
Epoch 66/100
27/27 [==============================] - 0s 1ms/step - loss: 0.2153 - accuracy: 0.9403
Epoch 67/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2786 - accuracy: 0.9054
Epoch 68/100
27/27 [==============================] - 0s 1ms/step - loss: 0.2397 - accuracy: 0.9061
Epoch 69/100
27/27 [==============================] - 0s 1ms/step - loss: 0.1992 - accuracy: 0.9543
Epoch 70/100
27/27 [==============================] - 0s 1ms/step - loss: 0.2377 - accuracy: 0.9127
Epoch 71/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2389 - accuracy: 0.9163
Epoch 72/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2091 - accuracy: 0.9370
Epoch 73/100
27/27 [==============================] - 0s 1ms/step - loss: 0.2208 - accuracy: 0.9294
Epoch 74/100
27/27 [==============================] - 0s 1ms/step - loss: 0.2709 - accuracy: 0.9142
Epoch 75/100
27/27 [==============================] - 0s 1ms/step - loss: 0.2158 - accuracy: 0.9330
Epoch 76/100
27/27 [==============================] - 0s 1ms/step - loss: 0.2471 - accuracy: 0.9174
Epoch 77/100
27/27 [==============================] - 0s 1ms/step - loss: 0.1650 - accuracy: 0.9463
Epoch 78/100
27/27 [==============================] - 0s 1ms/step - loss: 0.1985 - accuracy: 0.9397
Epoch 79/100
27/27 [==============================] - 0s 1ms/step - loss: 0.2286 - accuracy: 0.9320
Epoch 80/100
27/27 [==============================] - 0s 1ms/step - loss: 0.2104 - accuracy: 0.9375
Epoch 81/100
27/27 [==============================] - 0s 1ms/step - loss: 0.1970 - accuracy: 0.9270
Epoch 82/100
27/27 [==============================] - 0s 1ms/step - loss: 0.2137 - accuracy: 0.9217
Epoch 83/100
27/27 [==============================] - 0s 1ms/step - loss: 0.2271 - accuracy: 0.9082
Epoch 84/100
27/27 [==============================] - 0s 1ms/step - loss: 0.2060 - accuracy: 0.9466
Epoch 85/100
27/27 [==============================] - 0s 1ms/step - loss: 0.1950 - accuracy: 0.9248
Epoch 86/100
27/27 [==============================] - 0s 2ms/step - loss: 0.2485 - accuracy: 0.8936
Epoch 87/100
27/27 [==============================] - 0s 1ms/step - loss: 0.1805 - accuracy: 0.9308
Epoch 88/100
27/27 [==============================] - 0s 1ms/step - loss: 0.2429 - accuracy: 0.9196
Epoch 89/100
27/27 [==============================] - 0s 1ms/step - loss: 0.1870 - accuracy: 0.9481
Epoch 90/100
27/27 [==============================] - 0s 1ms/step - loss: 0.1748 - accuracy: 0.9502
Epoch 91/100
27/27 [==============================] - 0s 1ms/step - loss: 0.1780 - accuracy: 0.9403
Epoch 92/100
27/27 [==============================] - 0s 1ms/step - loss: 0.2026 - accuracy: 0.9304
Epoch 93/100
27/27 [==============================] - 0s 2ms/step - loss: 0.1493 - accuracy: 0.9544
Epoch 94/100
27/27 [==============================] - 0s 2ms/step - loss: 0.1834 - accuracy: 0.9365
Epoch 95/100
27/27 [==============================] - 0s 2ms/step - loss: 0.1936 - accuracy: 0.9452
Epoch 96/100
27/27 [==============================] - 0s 2ms/step - loss: 0.1797 - accuracy: 0.9375
Epoch 97/100
27/27 [==============================] - 0s 2ms/step - loss: 0.1767 - accuracy: 0.9423
Epoch 98/100
27/27 [==============================] - 0s 2ms/step - loss: 0.1994 - accuracy: 0.9394
Epoch 99/100
27/27 [==============================] - 0s 2ms/step - loss: 0.1640 - accuracy: 0.9466
Epoch 100/100
27/27 [==============================] - 0s 1ms/step - loss: 0.1624 - accuracy: 0.9532

In [60]:
prediction = model.predict(x_test)

In [61]:
model.evaluate(x_test, y_test)

5/5 [==============================] - 0s 2ms/step - loss: 0.4081 - accuracy: 0.8156

[0.40811166167259216, 0.8156028389930725]

In [62]:
prediction.shape

(141, 1)

In [63]:
prediction.reshape(141)

array([0.37448806, 0.02285525, 0.8066006 , 0.04351759, 0.78342247,
       0.015279  , 0.9699738 , 0.09765241, 0.99724996, 0.05472648,
       0.9888878 , 0.05681083, 0.04185748, 0.04626781, 0.96995795,
       0.25845712, 0.03683257, 0.04570684, 0.7446084 , 0.9637363 ,
       0.11368978, 0.8754569 , 0.01988894, 0.08148116, 0.07316643,
       0.93228376, 0.24436098, 0.9717657 , 0.12102377, 0.33986136,
       0.80181366, 0.99185276, 0.08770078, 0.07672006, 0.0332197 ,
       0.11712709, 0.04152387, 0.02822325, 0.3673888 , 0.05039257,
       0.0341754 , 0.04270598, 0.12811676, 0.05829376, 0.56465364,
       0.7231002 , 0.07174698, 0.04296076, 0.04314098, 0.2253454 ,
       0.06040776, 0.21006331, 0.27071053, 0.9526484 , 0.9196353 ,
       0.9863425 , 0.9477744 , 0.04950047, 0.4966357 , 0.02200487,
       0.04805487, 0.05682066, 0.03395674, 0.02553618, 0.26207906,
       0.8001653 , 0.07209304, 0.1070565 , 0.04003739, 0.093961  ,
       0.08463985, 0.14411816, 0.06579825, 0.04479191, 0.04374677,
       0.03472313, 0.0380905 , 0.4822244 , 0.02677071, 0.24887866,
       0.04920179, 0.05085081, 0.8982954 , 0.0490939 , 0.02452165,
       0.07625762, 0.9974365 , 0.06954098, 0.01715732, 0.07641065,
       0.12373233, 0.24579144, 0.02660739, 0.06302896, 0.04588079,
       0.05261829, 0.9889036 , 0.6557487 , 0.03310668, 0.9687035 ,
       0.24639854, 0.3139071 , 0.05406037, 0.8220757 , 0.02418754,
       0.99669105, 0.34356093, 0.12625787, 0.7991811 , 0.04873085,
       0.9972688 , 0.61128926, 0.08070105, 0.02834061, 0.08185887,
       0.04566583, 0.03026071, 0.2989316 , 0.05443326, 0.04431129,
       0.3743379 , 0.40700662, 0.14098114, 0.12287471, 0.37705943,
       0.995879  , 0.04202971, 0.15295428, 0.06083894, 0.438398  ,
       0.02100202, 0.6479966 , 0.05321938, 0.13855714, 0.01842681,
       0.06770352, 0.06254399, 0.07229078, 0.37596548, 0.17816186,
       0.05387607], dtype=float32)